# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "3456:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
